### ISSUE TITLE
admiraldev renv.lock not automatically installing admiral.test

### ISSUE THREAD

**Issue by esimms999-gsk** [pharmaverse/admiralci#103]
@pharmaverse/admiral NOTE: I put this issue in admiralci even though the problem is showing up when I want to work on admiraldev.

I start a new project in RStudio based off of the admiraldev repo, switch to devel branch, do renv::activate(profile="4.2") (I am using R 4.2.3) and renv::restore(). I notice that, unlike admiral, the admiral.test@devel is not automatically installed:

![admiral_test](https://user-images.githubusercontent.com/85294667/235776959-2b950518-b654-4f6d-b61f-b6e8748173bb.png)

I go ahead and do the Build->Check and there are errors because admiral.test is not available:

![admiral_test_error](https://user-images.githubusercontent.com/85294667/235777254-377f5b2f-d11a-4fcd-8150-c04a4610af96.png)

If I manually install admiral.test@devel and re-run the Build->Check, it works ok:

![check_ok](https://user-images.githubusercontent.com/85294667/235777510-240ab299-e0ee-4742-98e0-6a28a2319342.png)

**Comment by bms63** [comment]
I don't think we have used `renv.lock` to install `admiral.test` for a while now.  We removed it when we started using stage dependencies I believe.  The same for `admiraldev`

**Comment by esimms999-gsk** [comment]
I thought that changes had been made, recently, to load admiraldev@devel and admiral.test@devel automatically when doing renv::restore() in admiral. And, therefore, I expected admiral.test@devel to be loaded automatically when doing renv::restore() in admiraldev. 
I did a test and it looks like all of this requires manual loads, i.e. not being done in the renv::restore().

I will close this.
