### ISSUE TITLE
Bug: The searchbar on the pkgdown website is not working properly

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralci#110]
### What happened?

The searchbar on the pkdown website is not working properly. If on the cran-release version of the site, making a search returns you to the v0.10.2 version of the site. If on older version, you get a 404 error.

### Session Information

NA

### Reproducible Example

See what happened section

**Comment by bundfussr** [comment]
The linking across admiral packages does not work. E.g., on the admiralonco page links referring to admiral functions do not point to the admiral site. Could be related to multi-versions docs.

**Comment by bms63** [comment]
@cicdguy and @dgrassellyb do you think we can fix this before the June 5th release?

**Comment by bundfussr** [comment]
Could we document somewhere how to set up the `pkgdown` config such that the search and linking across packages work?

**Comment by bms63** [comment]
@cicdguy is this going to fixed or should we put onto next release?
