### ISSUE TITLE
Add functionality to automatically identify stale issues/PRs

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralci#124]
See [here](https://github.com/actions/stale) - would be nice to have a coordinated approach across the `{admiral}` family. My proposition would be a two week period before issues/PRs are marked as stale.

@pharmaverse/admiral what are your thoughts?

**Comment by bms63** [comment]
I'm all in - bots are back in town!  We have several issues that are over two years old and some approaching that marker.  

Honestly, if we can get any activity or work on them, then I think that is indicative of the issue being poorly formed or just too broad for someone to address.  I don't think issues should become legacy issues where we keep them open forever.

**Comment by StefanThoma** [comment]
This has been implemented already, right?

**Comment by manciniedoardo** [comment]
It's active on the {admiral} repo but not sure about the other repos.

**Comment by bms63** [comment]
Implemented in admiral - I think the other repos don't need this.
