### ISSUE TITLE
Load renv/profiles for container context

### ISSUE THREAD

**Issue by dgrassellyb** [pharmaverse/admiralci#126]
For now the .Rprofile has this following content : 

```
# Set renv profile base on R version.
if ((Sys.getenv("GITHUB_ACTIONS") == "") && (Sys.getenv("DOCKER_CONTAINER_CONTEXT") == "")) {
  renv_profile <- paste(R.version$major, substr(R.version$minor, 1, 1), sep = ".")
  if (file.exists("./renv/profile")) {
    message("Using renv profile from `renv/profile` file.")
  } else if (renv_profile %in% c("4.1", "4.2", "4.3")) {
    message("Set renv profile to `", renv_profile, "`")
    Sys.setenv("RENV_PROFILE" = renv_profile)
  } else {
    message("This repository do not contains the renv profile for your R version.")
  }
  source("renv/activate.R")
} else {
  options(repos = c(CRAN = "https://cran.rstudio.com/"))
}
```

we should load the proper renv/profile also on containers 
There is for now an issue calling 'source("renv/activate.R")' script - it's reinstalling renv library (and then breaking existing dependencies) - this reinstallation is caused by `renv_bootstrap_load` function failing 

TODO: 
- debug renv_bootstrap_load function (understand why it's failing - probably due to some env variables to set-up)
- once it's debug, update .Rprofile file (as well for other pharmaverse packages using docker images)

**Comment by galachad** [comment]
HI @dgrassellyb, I'm closing this issue as it's resolved, please reopen if needed. Thanks
