### ISSUE TITLE
Linkage between admiral sites is broken

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiralci#131]
@cicdguy @galachad @dgrassellyb 

Hi all,

We noticed that the links between admiral packages are broken since we moved to the versioning system of the website.  

For example, in the [vignette ](https://pharmaverse.github.io/admiralonco/main/articles/adrs.html) `derive_vars_merged()` links out to a fallback page at https://rdrr.io/cran/admiral/man/derive_vars_merged.html, but we would like it to go to the admiral page for `derive_vars_merged()`

![image](https://github.com/pharmaverse/admiralci/assets/10111024/b06aa85c-f147-4f03-ba9d-2a0b9e18c557)

**Comment by ddsjoberg** [comment]
Thanks for the link @cicdguy ! While I still need to review the linked issues, my first guess is the auto-linking broke when the main site was moved to a subfolder within the `gh-pages` branch. (By default, pkgdown will place the static website files in the root of `gh-pages`.)

Related and discussed today in the admiral meeting today:
- [ ] move the primary website the default pkgdown location, aka the `gh-pages` root.
- [ ] use the pkgdown built-in infrastructure for serving the dev site from a dev folder 
    ```yaml
    development:
      mode: auto
      version_label: default
    ```
    
- [ ] The version menu on the website will only continue to grow. Proposal to reduce the list to "Development", "Current Release", and "Prior Releases". The "Prior Releases" would link to a separate page that would then list every prior release's website. My preference would be to put these release websites in a subfolder `gh-pages/prior-releases`. There is currently one folder for each release website in the root of the branch.

**Comment by galachad** [comment]
Hi @bms63 and @ddsjoberg I made the links tweak that will fix the issue with linking package to pharmaverse docs. https://github.com/pharmaverse/admiralvaccine/pull/221 we can make it global in `admiralci` or have the tweaks in every package separately.
