### ISSUE TITLE
Update `{admiral.test}` references to `{pharmaversesdtm}`

### ISSUE THREAD

**Issue by jeffreyad** [pharmaverse/admiralci#139]
References to `{admiral.test}` should be updated to `{pharmaversesdtm}` to reflect change in source SDTM data.

**Comment by galachad** [comment]
Hi @jeffreyad, should we add `pharmaversesdtm` to propagation `(renv, devcontainer, .Rpofile, ...)`?

**Comment by jeffreyad** [comment]
> Hi @jeffreyad, should we add `pharmaversesdtm` to propagation `(renv, devcontainer, .Rpofile, ...)`?

Yes, `admiral.test` should be replaced with `pharmaversesdtm`.  Thanks

**Comment by galachad** [comment]
Hi @jeffreyad, the [`staged_dependencies.yaml`](https://github.com/pharmaverse/admiral/blob/devel/staged_dependencies.yaml) should be updated in every repository separately.  I will add the changes in propagation PR and will tag you as reviewer.
