### ISSUE TITLE
Link workflows documentation with title of PR Action

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiralci#15]
I was thinking that we should link these with the appropriate titles in the PR Actions.  I don't think they line up exactly and new developers are often unsure which one is which and what they are doing.  Some are super obvious, i.e. lint.yml with the Lint check.

![image](https://user-images.githubusercontent.com/10111024/191532451-b45e6a65-a853-4125-9b1c-74a70f560691.png)

![image](https://user-images.githubusercontent.com/10111024/191544893-52f6cc58-2eda-46e0-aa79-260d4b8c2d82.png)

**Comment by zdz2101** [comment]
I am interested in getting a little more exposure to this DevOps type of stuff and I think this would be a "good first issue" for me, @bms63 can you grant me access to the repo?

**Comment by bms63** [comment]
Added to repo
