### ISSUE TITLE
Add vbump workflow

### ISSUE THREAD

**Issue by ddsjoberg** [pharmaverse/admiralci#155]
When the dust settles from the latest patch release and the many open PRs are merged, we discussed adding the vbump workflow to admiral.

### Additional Context

In the DESCRIPTION file we `bump` the version up to X.Y.Z.9000 to designate the development version of the package.  I believe we should be incrementing 0.0001 as we make updates.  This incrementing could introduce some tedious merge conflicts as well as be forgotten by developers/reviewers/

I believe `vbump` was to help automate this through the Pull Request, i.e. the PR would help to increment the version number instead of the developer.  @ddsjoberg do you have any other thoughts?

This is a nice to have but a low priority.  

[Reference workflow is here.](https://github.com/insightsengineering/r.pkg.template/blob/main/.github/workflows/version-bump.yaml)

**Comment by bms63** [comment]
@cicdguy @dgrassellyb

**Comment by dgrassellyb** [comment]
> When the dust settles from the latest patch release and the many open PRs are merged, we discussed adding the vbump workflow to admiral.
> 
> ### Additional Context
> In the DESCRIPTION file we `bump` the version up to X.Y.Z.9000 to designate the development version of the package. I believe we should be incrementing 0.0001 as we make updates. This incrementing could introduce some tedious merge conflicts as well as be forgotten by developers/reviewers/
> 
> I believe `vbump` was to help automate this through the Pull Request, i.e. the PR would help to increment the version number instead of the developer. @ddsjoberg do you have any other thoughts?
> 
> This is a nice to have but a low priority.
> 
> [Reference workflow is here.](https://github.com/insightsengineering/r.pkg.template/blob/main/.github/workflows/version-bump.yaml)

@cicdguy what are your thoughts on this ? not even sure if a PR is needed, we could just automatically push the changes since it's just an automatic vbump after new changes..? (I mean I am not sure it would need a review but maybe I'm wrong !)
