### ISSUE TITLE
workflows removed documentation of older versions

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiralci#177]
It seems that the workflows have removed the documentation of older versions of admiral (see https://github.com/pharmaverse/admiral/commit/df260688902d7f35bc759da76ed2b9fd80a5d535).

**Comment by ddsjoberg** [comment]
@dgrassellyb @cicdguy please let me know if you'd like me to assist in the fix.
My guess is that there is a `pkgdown::deploy_to_branch()` that needs a `clean=FALSE` argument added. We'll also need to restore the previous version folders that were in the root of the `gh-pages` branch.

Can we please prioritize this fix and restoring the previous version sites?

**Comment by dgrassellyb** [comment]
> @dgrassellyb @cicdguy please let me know if you'd like me to assist in the fix. My guess is that there is a `pkgdown::deploy_to_branch()` that needs a `clean=FALSE` argument added. We'll also need to restore the previous version folders that were in the root of the `gh-pages` branch.
> 
> Can we please prioritize this fix and restoring the previous version sites?

Indeed seems like we should use this CLEAN=False option (https://pkgdown.r-lib.org/reference/deploy_to_branch.html?q=deploy_to_branch#ref-usage) - I can rollback to previous commit and try another deployment with this option !

**Comment by dgrassellyb** [comment]
just simulated a new release (after restoring gh-pages + clean=FALSE arg) in my forked admiral repo, if someone want to cross-check everything is okay : 
https://dgrassellyb.github.io/admiral/ (@ddsjoberg / @bundfussr )

**Comment by bundfussr** [comment]
> just simulated a new release (after restoring gh-pages + clean=FALSE arg) in my forked admiral repo, if someone want to cross-check everything is okay : https://dgrassellyb.github.io/admiral/ (@ddsjoberg / @bundfussr )

I get
![image](https://github.com/pharmaverse/admiralci/assets/80953585/dbf4f080-426e-44c1-9531-ec7ae4e184af)
when using the links on the "Previous Versions of Website". So there is still something wrong.

**Comment by dgrassellyb** [comment]
> Previous Versions of Website

It's because I restored previous versions, so it contains links to admiral official doc (pharmaverse.github.io/admiral) - if you replace it with my "forked doc" (replace just pharmaverse by dgrassellyb) the link will work

**Comment by bundfussr** [comment]
> > Previous Versions of Website
> 
> It's because I restored previous versions, so it contains links to admiral official doc (pharmaverse.github.io/admiral) - if you replace it with my "forked doc" (replace just pharmaverse by dgrassellyb) the link will work

I see. Thanks.
