### ISSUE TITLE
Fix Navigation Across Different Versions

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiralci#179]
It seems that the navigation across different versions of the package does not work.
- For the old versions we still have the old versions menu, i.e., you can't get back to the latest version. (In the old workflows the versions menu was updated for all versions if a new version was released.)
- The release did not trigger the creation of a `v1.0.0` folder in `gh-pages`, i.e., you can't get back from the development version to the latest released version.

**Comment by ddsjoberg** [comment]
- the old versions of the website are likely going to visited with relative low frequency, and I would suggest we keep things simple (ie the version folders are a copy of what the website looked like on the day of the release) as opposed to a more complex strategy that makes maintenance more difficult. Users will always have their browser's back button to return to the current release if that is what they need.
- @dgrassellyb do you know why the releases didn't trigger the creation of the `v1.0.0` folders? good catch!

**Comment by bundfussr** [comment]
> * the old versions of the website are likely going to visited with relative low frequency, and I would suggest we keep things simple (ie the version folders are a copy of what the website looked like on the day of the release) as opposed to a more complex strategy that makes maintenance more difficult.

In my experience, users are using old versions forever. Thus I would expect that users and health authorities visit the website of old versions frequently.

Why did we change it? It was working well before.

**Comment by ddsjoberg** [comment]
> In my experience, users are using old versions forever. Thus I would expect that users and health authorities visit the website of old versions frequently.

If that is the case, then the users don't need to navigate among _all_ available versions?

Maintaining a straightforward vignette is simpler than complex GH workflows.
