### ISSUE TITLE
Propagate new `renv.lock` and updating `common.yml`

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiralci#24]
@cicdguy 

Can we send out/propagate the `renv.lock` file to all the repos with updated version of R - `4.0`?  

I wanted to change the `common.yml` workflow to use 4.0 as well, but thought this should happen first.

![image](https://user-images.githubusercontent.com/10111024/195369479-a1a9f81a-0a9e-435a-ae3c-2e156876832f.png)

**Comment by bms63** [comment]
@walkowif how goes the progress?  Can I help in anyway?

**Comment by walkowif** [comment]
@bms63 This week my availability will be limited, so I may only be able to start working on this at the end of this week or next week.
