### ISSUE TITLE
Check Template fail on both warnings and errors

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiralci#27]
When we deprecate a function it emits a warning in a release and later an error in the next release.  Since we have quite a few templates it would be good to know if a deprecated function is being used before it starts getting an error.

**Comment by bms63** [comment]
https://stackoverflow.com/questions/56589407/how-to-get-an-rscript-to-return-a-status-code-in-non-interactive-bash-mode

**Comment by thomas-neitmann** [comment]
Simply setting `options(warn = 2)` inside the workflow will ensure all warnings are converted to errors and thus make the workflow fail.

**Comment by bms63** [comment]
@thomas-neitmann  aren't you asleep?

**Comment by bms63** [comment]
I was messing around with it and the template file sends this code out to Linux Rscript.  So I think it is executing in a different environment then where options(warn=2) is set.  

![image](https://user-images.githubusercontent.com/10111024/196995059-1eb125ae-5266-4647-84f1-0ae45d0ed473.png)
