### ISSUE TITLE
assertthat removed from `admiral` lock file

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiralci#38]
We are removing this package from `admiral` and `admiraldev`.  I think we can remove from lock propagation as well.  Just putting note here to check back on this.

![image](https://user-images.githubusercontent.com/10111024/201717130-59ea4a2a-8608-4bdd-86e3-9a2ff96996bd.png)

**Comment by rossfarrugia** [comment]
And new `renv.lock` propagation step since {admiraldev} updates, and part of release process for future?

**Comment by galachad** [comment]
The assertthat is still in used in [admiralophtha](https://github.com/pharmaverse/admiralophtha/tree/devel) and first need to be removed from there.

**Comment by rossfarrugia** [comment]
@millerg23 @manciniedoardo FYI of above for admiralophtha. I traced this back to a couple of issues for more context:
https://github.com/pharmaverse/admiral/issues/1392
https://github.com/pharmaverse/admiraldev/issues/149

**Comment by galachad** [comment]
https://github.com/pharmaverse/admiralophtha/issues/115 was fixed, now, we can remove assertthat from renv.
