### ISSUE TITLE
Automate `renv.lock` creation

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiralci#51]
The creation of `renv.lock` should be automated. A script should be implemented which creates `renv.lock` fulfilling the following requirements:
- The lock file should contain all packages which are imported or suggested by any of the admiral packages. The version of the packages should be the one which was available when the R version we are using for development was released. At the moment we use R 4.0. I.e., we would store the version in the lock file which was available when R 4.0 was released.
- There should be an option to use newer versions for some packages. For example, we use a newer version of pkgdown. The packages and versions should be stored in a separate file. It is read in by the script. Then the exceptions are clear and easy to maintain.
- The admiral packages should not be in the lock file because these are handled by staged_dependencies.

**Comment by bundfussr** [comment]
@bms63 , @galachad , @cicdguy ,  @walkowif , could you have a look? Does this make sense?

**Comment by bms63** [comment]
Yes makes sense.  I'll start trying to incorporate this into the vignette as well

**Comment by galachad** [comment]
This make sense, I will implement this.

I still think using custom method for generate dependencies is the best option `options(renv.snapshot.filter = .gen_dep_func)`

One more question is about `suggest` package section from `admiraldev`. In my opinion, all these packages should be included into `renv.lock`. Do you agree? 

```
Suggests:
    admiral.test,
    devtools,
    diffdf,
    lintr,
    pkgdown,
    testthat,
    knitr,
    methods,
    miniUI,
    rmarkdown,
    roxygen2,
    rstudioapi,
    spelling,
    styler,
    tibble,
    usethis,
    covr,
    DT
```

**Comment by bundfussr** [comment]
@galachad , yes, packages from `suggests` should be included because they are needed for developing (and `renv.lock` should provide the environment for developing).

**Comment by bms63** [comment]
> This make sense, I will implement this.
> 
> I still think using custom method for generate dependencies is the best option `options(renv.snapshot.filter = .gen_dep_func)`
> 
> One more question is about `suggest` package section from `admiraldev`. In my opinion, all these packages should be included into `renv.lock`. Do you agree?
> 
> ```
> Suggests:
>     admiral.test, (this one will be exclude from list)
>     devtools,
>     diffdf,
>     lintr,
>     pkgdown,
>     testthat,
>     knitr,
>     methods,
>     miniUI,
>     rmarkdown,
>     roxygen2,
>     rstudioapi,
>     spelling,
>     styler,
>     tibble,
>     usethis,
>     covr,
>     DT
> ```

A quick glance at the `renv.lock` file I see most of these there in `admiral` and `admiraldev`
