### ISSUE TITLE
Update snapshot dates so testthat >= 3.1.0 is available

### ISSUE THREAD

**Issue by nicholas-masel** [pharmaverse/admiralci#61]
I need to leverage snapshot variants to address differences due to the version of R.  Can we update R4.0 to a later snapshot [here](https://github.com/pharmaverse/admiralci/blob/main/.github/workflows/r-cmd-check.yml#L37)?  Anything after 04OCT2021 has testthat >= 3.1.  [Here it is on package manager](https://packagemanager.rstudio.com/client/#/repos/2/packages/testthat)

Since MRAN is going away, do we also want to go ahead and use package manager for all snapshots?

**Comment by galachad** [comment]
Done with renv propagation.

**Comment by nicholas-masel** [comment]
> Done with renv propagation.

So the renv propagation will also update the [snapshot dates for the r-cmd action](https://github.com/pharmaverse/admiralci/blob/main/.github/workflows/r-cmd-check.yml#L37)?  Sorry, I'm not seeing this linked and I poked around and cannot find where the action is updated.  Is this in #51?

**Comment by galachad** [comment]
We just need to merge these changes for cmd check, there is #63 to track this. The changes for renv was done when the propagation PR was merged.
