### ISSUE TITLE
Adopt versioning and changelog for admiralci

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiralci#65]
Going forward `admiralci` should up-version the description file every time there is an `admiral` release.

We should also start using a changelog to track changes of what has happened/updated/adopted into admiralci at each "release"

I think a simple PR template would be handy to remind us of a few simple updates to makes, e.g.

- [ ] Changelog/News/md update with Issue # and short description of what was addressed
- [ ] Check Description file has been up-versioned from last release
- [ ] Documentation is up to date with your changes, e.g. Vignette, Readme.
- [ ] Communication to wider team of upcoming CI changes

@cicdguy and @galachad what do you think?

**Comment by galachad** [comment]
I think we are not planing to release the admiralci as a package. This package is used for GitHub actions. 

I totally agree that we should add versioning, but it should be for GitHub actions. I would avoid complicating the versioning too much, so we should keep it simple.

For the changelog, we can try some automated generated changelog.

**Comment by bms63** [comment]
Right.  Same page on admiralci is never going to be released as an R package. 

I was thinking the easiest way to version the "package" is to just up-version with a release of admiral.   

I like the automated changelog!!  I've seen that option in the release, which would be very cool to start using.  I'm guessing we would have to be a more precise with our commit messages?

**Comment by bms63** [comment]
@dgrassellyb is it worthwhile to track changes in `admiralci` ??  - I don't really make a lot of changes here so leave it to you if you think changelog/versioning is important to this process.

**Comment by dgrassellyb** [comment]
> @dgrassellyb is it worthwhile to track changes in `admiralci` ?? - I don't really make a lot of changes here so leave it to you if you think changelog/versioning is important to this process.

Sorry just saw your message ! I don't think it's necessary to track changes in admiralci !
