### ISSUE TITLE
pkgdown action erroring out

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiralci#66]
Hey @cicdguy @dgrassellyb @galachad 

I merged in a PR for admiraldev into the `devel` branch and the page deployment is failing.  I think some of this is the hook code that was jsut merged into admiralci.  Any ideas?

![image](https://user-images.githubusercontent.com/10111024/220738765-41a42034-29d0-4f8b-9ff0-a321819a9367.png)

https://github.com/pharmaverse/admiraldev/actions/runs/4245613987/jobs/7382218526

##[debug]Evaluating condition for step: 'Publish documentation'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Publish documentation
##[debug]Loading inputs
##[debug]Evaluating: format('git config --local user.email "actions@github.com"
##[debug]git config --local user.name "GitHub Actions"
##[debug]SUBDIR_OPTION=""
##[debug]if [ "{0}" != "true" ]
##[debug]then {{
##[debug]  SUBDIR_OPTION="subdir = \"${{GITHUB_REF##*/}}\","
##[debug]}}
##[debug]fi
##[debug]Rscript - <<EOF
##[debug]
##[debug]pkgdown_env <- asNamespace("pkgdown")
##[debug]rlang::env_unlock(env = pkgdown_env)
##[debug]rlang::env_binding_unlock(env = pkgdown_env)
##[debug]# Modify tweak_page
##[debug]pkgdown_env$call_hook <- function(hook_name, ...) {{
##[debug]  # Get hooks from base::getHook
##[debug]  hooks <- getHook(paste0("UserHook::admiralci::", hook_name))
##[debug]  if (!is.list(hooks)) {{
##[debug]    hooks <- list(hooks)
##[debug]  }}
##[debug]
##[debug]  # Evaluate hooks
##[debug]  purrr::map(hooks, function(fun) {{
##[debug]    fun(...)
##[debug]  }}) %>%
##[debug]    invisible()
##[debug]}}
##[debug]environment(pkgdown_env$call_hook) <- pkgdown_env
##[debug]
##[debug]tweak_page <- body(pkgdown_env$tweak_page)
##[debug]body(pkgdown_env$tweak_page) <-
##[debug]  as.call(
##[debug]    append(
##[debug]      as.list(tweak_page),
##[debug]      expression(call_hook("tweak_page", html, name, pkg)),
##[debug]      after=length(tweak_page)
##[debug]    )
##[debug]  )
##[debug]
##[debug]rlang::env_binding_lock(env = pkgdown_env)
##[debug]rlang::env_lock(pkgdown_env)
##[debug]
##[debug]# Load package
##[debug]require(desc::desc_get("Package"), character.only = TRUE)
##[debug]
##[debug]pkgdown::deploy_to_branch(
##[debug]  new_process = FALSE,
##[debug]  ${{SUBDIR_OPTION}}
##[debug]  clean = TRUE
##[debug])
##[debug]EOF
##[debug]', inputs.skip-multiversion-docs)
##[debug]Evaluating format:
##[debug]..Evaluating String:
##[debug]..=> 'git config --local user.email "actions@github.com"
##[debug]git config --local user.name "GitHub Actions"
##[debug]SUBDIR_OPTION=""
##[debug]if [ "{0}" != "true" ]
##[debug]then {{
##[debug]  SUBDIR_OPTION="subdir = \"${{GITHUB_REF##*/}}\","
##[debug]}}
##[debug]fi
##[debug]Rscript - <<EOF
##[debug]
##[debug]pkgdown_env <- asNamespace("pkgdown")
##[debug]rlang::env_unlock(env = pkgdown_env)
##[debug]rlang::env_binding_unlock(env = pkgdown_env)
##[debug]# Modify tweak_page
##[debug]pkgdown_env$call_hook <- function(hook_name, ...) {{
##[debug]  # Get hooks from base::getHook
##[debug]  hooks <- getHook(paste0("UserHook::admiralci::", hook_name))
##[debug]  if (!is.list(hooks)) {{
##[debug]    hooks <- list(hooks)
##[debug]  }}
##[debug]
##[debug]  # Evaluate hooks
##[debug]  purrr::map(hooks, function(fun) {{
##[debug]    fun(...)
##[debug]  }}) %>%
##[debug]    invisible()
##[debug]}}
##[debug]environment(pkgdown_env$call_hook) <- pkgdown_env
##[debug]
##[debug]tweak_page <- body(pkgdown_env$tweak_page)
##[debug]body(pkgdown_env$tweak_page) <-
##[debug]  as.call(
##[debug]    append(
##[debug]      as.list(tweak_page),
##[debug]      expression(call_hook("tweak_page", html, name, pkg)),
##[debug]      after=length(tweak_page)
##[debug]    )
##[debug]  )
##[debug]
##[debug]rlang::env_binding_lock(env = pkgdown_env)
##[debug]rlang::env_lock(pkgdown_env)
##[debug]
##[debug]# Load package
##[debug]require(desc::desc_get("Package"), character.only = TRUE)
##[debug]
##[debug]pkgdown::deploy_to_branch(
##[debug]  new_process = FALSE,
##[debug]  ${{SUBDIR_OPTION}}
##[debug]  clean = TRUE
##[debug])
##[debug]EOF
##[debug]'
##[debug]..Evaluating Index:
##[debug]....Evaluating inputs:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'skip-multiversion-docs'
##[debug]..=> false
##[debug]=> 'git config --local user.email "actions@github.com"
##[debug]git config --local user.name "GitHub Actions"
##[debug]SUBDIR_OPTION=""
##[debug]if [ "false" != "true" ]
##[debug]then {
##[debug]  SUBDIR_OPTION="subdir = \"${GITHUB_REF##*/}\","
##[debug]}
##[debug]fi
##[debug]Rscript - <<EOF
##[debug]
##[debug]pkgdown_env <- asNamespace("pkgdown")
##[debug]rlang::env_unlock(env = pkgdown_env)
##[debug]rlang::env_binding_unlock(env = pkgdown_env)
##[debug]# Modify tweak_page
##[debug]pkgdown_env$call_hook <- function(hook_name, ...) {
##[debug]  # Get hooks from base::getHook
##[debug]  hooks <- getHook(paste0("UserHook::admiralci::", hook_name))
##[debug]  if (!is.list(hooks)) {
##[debug]    hooks <- list(hooks)
##[debug]  }
##[debug]
##[debug]  # Evaluate hooks
##[debug]  purrr::map(hooks, function(fun) {
##[debug]    fun(...)
##[debug]  }) %>%
##[debug]    invisible()
##[debug]}
##[debug]environment(pkgdown_env$call_hook) <- pkgdown_env
##[debug]
##[debug]tweak_page <- body(pkgdown_env$tweak_page)
##[debug]body(pkgdown_env$tweak_page) <-
##[debug]  as.call(
##[debug]    append(
##[debug]      as.list(tweak_page),
##[debug]      expression(call_hook("tweak_page", html, name, pkg)),
##[debug]      after=length(tweak_page)
##[debug]    )
##[debug]  )
##[debug]
##[debug]rlang::env_binding_lock(env = pkgdown_env)
##[debug]rlang::env_lock(pkgdown_env)
##[debug]
##[debug]# Load package
##[debug]require(desc::desc_get("Package"), character.only = TRUE)
##[debug]
##[debug]pkgdown::deploy_to_branch(
##[debug]  new_process = FALSE,
##[debug]  ${SUBDIR_OPTION}
##[debug]  clean = TRUE
##[debug])
##[debug]EOF
##[debug]'
##[debug]Result: 'git config --local user.email "actions@github.com"
##[debug]git config --local user.name "GitHub Actions"
##[debug]SUBDIR_OPTION=""
##[debug]if [ "false" != "true" ]
##[debug]then {
##[debug]  SUBDIR_OPTION="subdir = \"${GITHUB_REF##*/}\","
##[debug]}
##[debug]fi
##[debug]Rscript - <<EOF
##[debug]
##[debug]pkgdown_env <- asNamespace("pkgdown")
##[debug]rlang::env_unlock(env = pkgdown_env)
##[debug]rlang::env_binding_unlock(env = pkgdown_env)
##[debug]# Modify tweak_page
##[debug]pkgdown_env$call_hook <- function(hook_name, ...) {
##[debug]  # Get hooks from base::getHook
##[debug]  hooks <- getHook(paste0("UserHook::admiralci::", hook_name))
##[debug]  if (!is.list(hooks)) {
##[debug]    hooks <- list(hooks)
##[debug]  }
##[debug]
##[debug]  # Evaluate hooks
##[debug]  purrr::map(hooks, function(fun) {
##[debug]    fun(...)
##[debug]  }) %>%
##[debug]    invisible()
##[debug]}
##[debug]environment(pkgdown_env$call_hook) <- pkgdown_env
##[debug]
##[debug]tweak_page <- body(pkgdown_env$tweak_page)
##[debug]body(pkgdown_env$tweak_page) <-
##[debug]  as.call(
##[debug]    append(
##[debug]      as.list(tweak_page),
##[debug]      expression(call_hook("tweak_page", html, name, pkg)),
##[debug]      after=length(tweak_page)
##[debug]    )
##[debug]  )
##[debug]
##[debug]rlang::env_binding_lock(env = pkgdown_env)
##[debug]rlang::env_lock(pkgdown_env)
##[debug]
##[debug]# Load package
##[debug]require(desc::desc_get("Package"), character.only = TRUE)
##[debug]
##[debug]pkgdown::deploy_to_branch(
##[debug]  new_process = FALSE,
##[debug]  ${SUBDIR_OPTION}
##[debug]  clean = TRUE
##[debug])
##[debug]EOF
##[debug]'
##[debug]Loading env
Run git config --local user.email "actions@github.com"
##[debug]/usr/bin/bash -e /home/runner/work/_temp/c48860c[2](https://github.com/pharmaverse/admiraldev/actions/runs/4245613987/jobs/7382218526#step:11:2)-7565-40c4-a2[3](https://github.com/pharmaverse/admiraldev/actions/runs/4245613987/jobs/7382218526#step:11:3)1-53c[4](https://github.com/pharmaverse/admiraldev/actions/runs/4245613987/jobs/7382218526#step:11:4)307a7c[5](https://github.com/pharmaverse/admiraldev/actions/runs/4245613987/jobs/7382218526#step:11:5)2.sh
##[debug]Skipping logging an issue for the matched line because the message is empty.
Error in environment(pkgdown_env) <- pkgdown_env : 
  replacement object is not an environment
Execution halted
Error: Process completed with exit code 1.
##[debug]Finishing: Publish documentation
0s
##[debug]Evaluating condition for step: 'Post Restore cache'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> false
##[debug]Result: false

**Comment by bms63** [comment]
Maybe we should revert back.  We have the log and error message for @galachad to look at tomorrow in the issue?

**Comment by galachad** [comment]
I wasn't noticed that the code lines were evaluated by shell first. I escape special characters, so it will be working as expected.
