### ISSUE TITLE
admiral.test should be removed from lock file

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiralci#79]
@galachad  and @cicdguy we don't need admiral.test in the lock file.  We should be using admiral.test 0.5 and not 0.4

![image](https://user-images.githubusercontent.com/10111024/228364572-c6a0e0a1-c4e1-4074-8034-c02902e8762f.png)

**Comment by galachad** [comment]
I will remove it from propagation.

**Comment by galachad** [comment]
The admiral.test was never part of renv lock. I update the settings in #77 to do not allow for snapshots.
