### ISSUE TITLE
r-cmd-check.yml:  error_on = 'note'

### ISSUE THREAD

**Issue by nicholas-masel** [pharmaverse/admiralci#8]
I have a use case where `r cmd check` will always give a note.  By design the package is using `attach()` to modify the search path.  `r cmd check` does not like this and kicks out this note:

```r
❯ checking R code for possible problems ... NOTE
  Found the following calls to attach():
  File ‘envsetup/R/autos.R’:
    attach(NULL, name = name_with_prefix)
    attach(NULL, name = name_with_prefix)
  File ‘envsetup/R/rprofile.R’:
    attach(config_minus_autos$paths, name = "envsetup:paths", pos = pos)
  See section ‘Good practice’ in ‘?attach’.
```

Is there any chance we can [lighten this restriction](https://github.com/pharmaverse/admiralci/blob/main/.github/workflows/r-cmd-check.yml#L88) or make it configurable without copying `r-cmd-check.yml` into my repo?

**Comment by cicdguy** [comment]
Yes, we can. I will add this feature.

**Comment by cicdguy** [comment]
@nicholas-masel - I've added the feature here: https://github.com/pharmaverse/admiralci/blob/f3e3800d15e94ebbe2aafb07bd3c8e06dae638a5/.github/workflows/common.yml.inactive#L67-L75

You can set that to fail on `warning` or `error` instead of `note` (which is the default).
