### ISSUE TITLE
`admiral` Docker images

### ISSUE THREAD

**Issue by cicdguy** [pharmaverse/admiralci#84]
The objective is to make a common set of Docker images that will be used for all admiral CI/CD workflows and for local development.

The advantages of doing so are:

1. Everyone has a consistent working environment (same version of R, same versions of packages) etc.
2. Portability of the Docker images will allow for CI/CD workflows to be run by anyone, anywhere, and much faster
3. Ease of maintenance of workspaces/working environments using a config-based approach

For execution:

1. Host Dockerfile(s) and Docker images in this repo
1. Leverage the widely used [`rocker` RStudio images](https://hub.docker.com/r/rocker/rstudio) as the base, and populate these with packages from the `renv.lock` file in this repo
1. Publish those images to GHCR (GitHub Container Registry) using a separate CI/CD workflow
1. Update all CI/CD workflows to use the containers derived from the images in this step

**Comment by esimms999-gsk** [comment]
Note that I do not have a -v option in the docker run command; this would be necessary to have persistent storage. I still need to figure that part out.

**Comment by esimms999-gsk** [comment]
@cicdguy Can you give me access to the admiralci repo? I would like to assign myself to this issue. Thanks.

**Comment by dgrassellyb** [comment]
Hi @esimms999-gsk, thanks for your comment and the work you've already done, your Dockerfile will be very helpful to start this issue ! I will start working on this but we can of course keep collaborating on this subject !
