### ISSUE TITLE
General Issue: Consider use of the HEAD(default) branch as devel

### ISSUE THREAD

**Issue by galachad** [pharmaverse/admiralci#89]
### Background Information

In most of the case when user install package from GitHub it's install HEAD(default) branch.

This issue is to consider setting a HEAD branch to devel. 

Pros:
- More easy start for currently development version.
- For development it can simplify the start process
- Easy to put integration with codespace as devel will be default branch
- Less difficult to apply workflow changes (do not need to touch main branch)

Cons:
- It can impact CI
- Needs to verify how `{stage.dependency}` handle default branch.
- Can cause incompatibility when non experience user install from GitHub on prd environment

I do not find any topic about that, but maybe it was already discussed in the past.

**Comment by galachad** [comment]
In my opinion, we should not change the branch strategy, the strategy will stay the same, only default branch should change. I think modify the branch strategy in pharmaverse projects is not worth effort right now.

**Comment by rossfarrugia** [comment]
> can we update all others repos? `admiralvaccine`, `admiralophtha`, `admiralonco` and `admiral.test` to point by default to devel.

Probably not relevant now if we remove the `devel` branches as part of this proposed change to GitHub-flow https://github.com/pharmaverse/admiral/issues/2003

**Comment by galachad** [comment]
Hi @rossfarrugia, we already change the default branch in admiral and admiraldev. In bigger scope we will migrate to single branch strategy as discussed on weekly, but we will do this step by step.

**Comment by bms63** [comment]
This was implemented, but we are now really moving to the GitHub Flow Strategy and dropping `devel`  https://github.com/pharmaverse/admiral/issues/2003
