### ISSUE TITLE
renv/activate.R needs to be listed in .gitignore?

### ISSUE THREAD

**Issue by esimms999-gsk** [pharmaverse/admiralci#94]
Issue #82 has been closed but I am still seeing renv/activate.R showing up as a staged file in the Git panel immediately after I do the renv::activate(profile="4.2") command. Can this file be listed in the admiral .gitignore file to keep this from happening?

![image](https://user-images.githubusercontent.com/85294667/233704098-742d90eb-35d0-4de1-a673-8166e21634a4.png)

**Comment by bms63** [comment]
Happy to discuss, but when I get assign an issue I should be working on it!  Feel free to tag me :) 
@bms63

**Comment by galachad** [comment]
We can not have the `renv/activate.R` in .gitignore as it's already existed in the repository. I need to verify why it's happens. 

In my opinion, it's cause by the renv version from the main branch. When the user start from the main branch, it's installing renv v16.0 and it's impacting activate file.

Changing the devel branch to default will probably solve this issue. 

The other idea will be removed the `renv/activate.R` and used it from separate location, but this need to be confirmed if it does not impact any of activation process.

**Comment by galachad** [comment]
This will not be a problem anymore, after migrating to single branch strategy.
